In [1]:
#2D ARRAY / INSERTING AN ELEMENT

In [2]:
import numpy as np

In [17]:
twodarray = np.array([[11,14,3,4],[3,4,5,1],[2,5,65,2],[6,8,9,9]])
print(twodarray)

[[11 14  3  4]
 [ 3  4  5  1]
 [ 2  5 65  2]
 [ 6  8  9  9]]


In [18]:
newtwo=np.insert(twodarray ,0,[[1,2,3,4]] ,axis=0)
print(newtwo)

[[ 1  2  3  4]
 [11 14  3  4]
 [ 3  4  5  1]
 [ 2  5 65  2]
 [ 6  8  9  9]]


In [19]:
newtwo=np.insert(twodarray ,1,[[1,2,3,4]] ,axis=0)
print(newtwo)

[[11 14  3  4]
 [ 1  2  3  4]
 [ 3  4  5  1]
 [ 2  5 65  2]
 [ 6  8  9  9]]


In [20]:
newtwo=np.insert(twodarray ,0,[[1,2,3,4]] ,axis=1)
print(newtwo)

[[ 1 11 14  3  4]
 [ 2  3  4  5  1]
 [ 3  2  5 65  2]
 [ 4  6  8  9  9]]


In [22]:
newtwo=np.insert(twodarray ,2,[[14,2,3,4]] ,axis=1)
print(newtwo)

[[11 14 14  3  4]
 [ 3  4  2  5  1]
 [ 2  5  3 65  2]
 [ 6  8  4  9  9]]


In [25]:
#2ND WAY (Using append we can add the new elements at the start or at the end of the row or column )

In [26]:
newtwo=np.append(twodarray ,[[1,2,3,4]] ,axis=0)
print(newtwo)

[[11 14  3  4]
 [ 3  4  5  1]
 [ 2  5 65  2]
 [ 6  8  9  9]
 [ 1  2  3  4]]
