In [1]:
#ACCESSING AN ELEMENT IN 2D ARRAY

In [2]:
import numpy as np

In [8]:
twodarray = np.array([[1,2,3,4],[4,5,3,5],[5,8,7,4],[21,5,3,5]])
print(twodarray)

[[ 1  2  3  4]
 [ 4  5  3  5]
 [ 5  8  7  4]
 [21  5  3  5]]


In [10]:
def accesselements(array ,rowindex , columnindex):
    if rowindex >=len(array) or   columnindex >=len(array[0]):
        print('INcorrect index')
    else:
        print(array[rowindex][columnindex])
accesselements(twodarray ,1,2)

3
