In [7]:
#DELETING ELEMENT FROM 2D ARRAY

In [8]:
import numpy as np
twodarray = np.array([[1,2,3,4],[3,4,5,6],[4,6,7,2],[9,8,6,4]])
print(twodarray)
newarray =np.delete(twodarray ,1,axis=1)
print(newarray)

[[1 2 3 4]
 [3 4 5 6]
 [4 6 7 2]
 [9 8 6 4]]
[[1 3 4]
 [3 5 6]
 [4 7 2]
 [9 6 4]]


In [9]:
twodarray = np.array([[1,2,3,4],[3,4,5,6],[4,6,7,2],[9,8,6,4]])
print(twodarray)
newarray =np.delete(twodarray ,0,axis=1)
print(newarray)

[[1 2 3 4]
 [3 4 5 6]
 [4 6 7 2]
 [9 8 6 4]]
[[2 3 4]
 [4 5 6]
 [6 7 2]
 [8 6 4]]


In [10]:
twodarray = np.array([[1,2,3,4],[3,4,5,6],[4,6,7,2],[9,8,6,4]])
print(twodarray)
newarray =np.delete(twodarray ,1,axis=0)
print(newarray)

[[1 2 3 4]
 [3 4 5 6]
 [4 6 7 2]
 [9 8 6 4]]
[[1 2 3 4]
 [4 6 7 2]
 [9 8 6 4]]


In [11]:
twodarray = np.array([[1,2,3,4],[3,4,5,6],[4,6,7,2],[9,8,6,4]])
print(twodarray)
newarray =np.delete(twodarray ,3,axis=0)
print(newarray)

[[1 2 3 4]
 [3 4 5 6]
 [4 6 7 2]
 [9 8 6 4]]
[[1 2 3 4]
 [3 4 5 6]
 [4 6 7 2]]
