In [1]:
#Q7 )ROTATE MATRIX 

In [2]:
import numpy as np

In [3]:
myarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myarray)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
def rotatematrix(matrix):
    n= len(matrix)
    for layer in range(n//2):
        first =layer
        last =n-layer-1
        for i in range (first,last):
            top=matrix[layer][i]
            matrix[layer][i]=matrix[-i-1][layer]
            matrix[-i-1][layer]=matrix[-i-1][layer]
            matrix[-layer-1][-i-1]=matrix[i][-layer-1]
            matrix[i][-layer-1]=top
        return matrix
print(rotatematrix(myarray))

[[7 4 1]
 [4 5 2]
 [7 6 3]]
