In [7]:
#SEARCHING AN ELEMENT IN 2D ARRAY

In [8]:
import numpy as np

In [9]:
twodarray = np.array([[1,2,3,4],[3,4,5,6],[4,6,7,2],[9,8,6,4]])
print(twodarray)

[[1 2 3 4]
 [3 4 5 6]
 [4 6 7 2]
 [9 8 6 4]]


In [10]:
def searchtwo(array , value):
    for i in range (len(array)):#returning no. of rows
        for j in range (len(array[0])):
            if array[i][j]==value:
                return 'The value is located at index '+str(i)+" "+str(j)
    return 'The element is not found'
searchtwo(twodarray,14)

'The element is not found'

In [11]:
def searchtwo(array , value):
    for i in range (len(array)):#returning no. of rows
        for j in range (len(array[0])):
            if array[i][j]==value:
                return 'The value is located at index '+str(i)+","+str(j)
    return 'The element is not found'
searchtwo(twodarray,6)

'The value is located at index 1,3'