# TRAVERSE AN ARRAY

In [2]:
import numpy as np
twodarray = np.array([[1,2,3,4],[4,2,1,4],[5,7,3,2],[8,9,4,2]])
print(twodarray)

[[1 2 3 4]
 [4 2 1 4]
 [5 7 3 2]
 [8 9 4 2]]


In [6]:
def traverse(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])
traverse(twodarray)

1
2
3
4
4
2
1
4
5
7
3
2
8
9
4
2
